### ISSUE TITLE
HOWTO ?

### ISSUE THREAD

**Issue by bashu** [ikresoft/django-url-browser#1]
Hey,

Thanks for the app, but can you explain how to use it? here what I managed to get, but it appears broken

![screen shot 2015-05-22 at 11 27 31](https://cloud.githubusercontent.com/assets/144783/7764623/6e5c67ce-006d-11e5-959d-33b6be0541aa.png)

**Comment by ikresoft** [comment]
@bashu it's still beta, I am trying to find time to finish this module, its very good idea for every thing you get this url browser its very good for cms for example. Design is very bad on standard django admin templates because I use django-suit bootstrap 2

**Comment by ikresoft** [comment]
I will make changes today for using with standard admin templates

**Comment by bashu** [comment]
Can you confirm that this app is working? do you have an example project or at least can you tell what filer/django/ckeditor/suit version to use?

**Comment by bashu** [comment]
no one cares
